version: "3.7"
services:
  nginx:
    image: nginx:1.16-alpine
    container_name: nginx_main
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
#      - wrp_network
#      - idolina_network
      - memo_network

networks:
#  wrp_network:
#    external:
#      name: wrp_wrp_network
#  idolina_network:
#    external:
#      name: idolina_idolina_network
  memo_network:
    external:
      name: memology_memo_network
