version: "3.7"
services:
  nginx:
    image: nginx:1.16-alpine
    container_name: nginx_main
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - wrp_network
      - wrp_global_network

networks:
  wrp_network:
    external:
      name: wrp_wrp_network
  wrp_global_network:
    external:
      name: wrp_wrp_global_network
